version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Africa/Cairo
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - abahmed
  - muhammednagy
  versioning-strategy: increase
